name: Android

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, test and distribute
    runs-on: ubuntu-latest
    steps:

    # several actions use checkout 
    - name: Install checkout
      uses: actions/checkout@v2
    
    ##############################################
    # flutter-action
    ##############################################
    # the flutter-action action seems to need java
    - name: Install Java, for building Flutter tool
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # use flutter-action configured with flutter channel
    - name: Install Flutter tool
      uses: subosito/flutter-action@v1
      with:
        channel: 'dev' # or: 'stable' or 'beta'

    ##############################################
    # setup-gcloud
    ##############################################
    # the setup-gcloud action seems to need python
    - name: Install python, for building gcloud
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    # use setup-gcloud configured with auth credentials 
    - name: Install gcloud and use gsutil to download credentials
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GSUTIL_SERVICE_ACC_EMAIL }}
        service_account_key: ${{ secrets.GSUTIL_SERVICE_ACC_PASSWORD }}

    - run: gsutil cp gs://crowdleague-credentials/google-services.json ./android/app/google-services.json
    - run: gsutil cp gs://crowdleague-credentials/keystore.jks ./android/app/keystore.jks
    - run: gsutil cp gs://crowdleague-credentials/keystore.config ./android/app/keystore.config
    - run: gsutil cp gs://crowdleague-credentials/crowdleague-fastlane-manager.json ./android/crowdleague-fastlane-manager.json
    
    - run: flutter pub get
    - run: flutter pub run build_runner build
    - run: flutter test
    - run: flutter build appbundle -t lib/app/main.dart --build-number=$GITHUB_RUN_NUMBER
    
    - run: brew install imagemagick
    - run: flutter pub global activate -sgit https://github.com/mmcc007/screenshots


    #############################################
    ## runs fastlane to deploy to play store 
    #############################################
    - name: Install fastlane and deploy to Play Store 
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'deploy_internal'
        subdirectory: 'android'