name: Github Actions

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - build
      - deploy

jobs:
  build:
    name: CI
    runs-on: macOS-latest
    
    steps:

    # output the build number used in this job
    - name: Output Run Info
      run: echo "build-number=$GITHUB_RUN_NUMBER, event = ${{ github.event_name }}, branch = ${{ github.ref }}, target = ${{ github.base_ref }}"

    # several actions use checkout
    - name: Install checkout
      uses: actions/checkout@v2
    
    ##############################################
    # flutter-action
    ##############################################
    # the flutter-action action needs java
    - name: Install Java for Flutter tool
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # use flutter-action configured with flutter channel
    - name: Install Flutter tool
      uses: subosito/flutter-action@v1
      with:
        channel: 'master' # or: 'stable' or 'beta'

    ##############################################
    # get dependencies & generate code
    ##############################################
    - name: Get app dependencies
      run: flutter pub get
    - name: Generate built_value code
      run: flutter pub run build_runner build

    ##############################################
    # run tests and upload coverage to coveralls
    ##############################################
    - name: Run tests and save coverage
      # run on PR for status check and on push for coverage
      if: ${{ github.base_ref == 'dev' || github.ref == 'refs/heads/dev' }}
      run: flutter test --coverage
    - name: Coveralls
      # run on push to dev branch, for the coverage
      if: ${{ github.base_ref == 'dev' || github.ref == 'refs/heads/dev' }}
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    ##############################################
    # setup-gcloud & download credential files 
    ##############################################
    # use setup-gcloud configured with auth credentials 
    - name: Setup gcloud for gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      if: github.ref == 'refs/heads/build'
      with:
        version: '290.0.1'
        service_account_email: ${{ secrets.GSUTIL_SERVICE_ACC_EMAIL }}
        service_account_key: ${{ secrets.GSUTIL_SERVICE_ACC_PASSWORD }}
    - name: Download credential files
      if: github.ref == 'refs/heads/build' || github.ref == 'refs/heads/deploy'
      run: ./.scripts/get-credentials.sh

    ############################################
    # build ios app and android app
    ############################################
    - name: Build for Android
      if: github.ref == 'refs/heads/build' || github.ref == 'refs/heads/deploy'
      run: flutter build appbundle --build-number=$GITHUB_RUN_NUMBER
    - name: Build for iOS (unsigned)
      if: github.ref == 'refs/heads/build' || github.ref == 'refs/heads/deploy'
      run: flutter build ios --release --no-codesign --build-number=$GITHUB_RUN_NUMBER

    ##############################################
    # use fastlane to build signed ios app 
    ##############################################
    - name: Build again for iOS (signed)
      if: github.base_ref == 'refs/heads/deploy'
      run: fastlane build_signed --verbose
      working-directory: ./ios

    # ##############################################
    # # setup and install screenshots package
    # ##############################################
    - name: Install ImageMagick for screenshots
      if: github.base_ref == 'refs/heads/deploy'
      run: brew install imagemagick

    - name: Install screenshots package 
      if: github.base_ref == 'refs/heads/deploy'
      run: flutter pub global activate -sgit https://github.com/mmcc007/screenshots

    # ############################################################
    # # setup android emulator with android-emulator-runner 
    # ############################################################
    - name: Add Android emulator and run screenshots
      if: github.base_ref == 'refs/heads/deploy'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        script: flutter pub global run screenshots:main

    # ##############################################
    # # use fastlane to deploy ios app 
    # ##############################################
    - name: Deploy to App Store
      if: github.base_ref == 'refs/heads/deploy'
      env:
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      run: fastlane deploy_internal --verbose
      working-directory: ./ios

    # ##############################################
    # # use fastlane to deploy android app 
    # ##############################################
    - name: Deploy to Play Store
      if: github.base_ref == 'refs/heads/deploy'
      run: fastlane deploy_internal --verbose
      working-directory: ./android
